import { useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import type { UserSkill } from "@/../../shared/schema";

export type ConstellationMilestone = { id: string; title: string; level?: number; x: number; y: number; parents?: string[] };
type Props = { skills: UserSkill[]; getMilestones: (skill: UserSkill) => ConstellationMilestone[]; getCustomIcon: (skill: UserSkill) => LucideIcon; pending: boolean; error?: Error | null; onRetry: () => void; onToggle: (id: number, milestoneId: string) => void; onEditSkill: (s: UserSkill) => void; onDeleteSkill: (s: UserSkill) => void; onAddSkill: () => void; onWhySkills: () => void; onEditMilestones: (s: UserSkill) => void };
const ORDER = ["Mindset", "Scholar", "Charisma", "Physical", "Artist", "Connector", "Craftsman", "Explorer", "Merchant", "Health"];
const COLORS: Record<string, string> = { Mindset: "#66e3e1", Scholar: "#b596ee", Charisma: "#e68eb4", Physical: "#f0d879", Artist: "#d77f8c", Connector: "#66e3e1", Craftsman: "#b596ee", Explorer: "#e68eb4", Merchant: "#f0d879", Health: "#d77f8c" };
const DESC: Record<string, string> = { Mindset: "transmute / reframe", Scholar: "study / synthesis", Charisma: "presence / influence", Physical: "strength / performance", Artist: "ideas / expression", Connector: "trust / belonging", Craftsman: "tools / creation", Explorer: "discovery / courage", Merchant: "value / leverage", Health: "vitality / longevity" };
const ICONS: Record<string, ReactNode> = {
  Mindset: <><circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4M5 5l3 3M16 16l3 3M19 5l-3 3M8 16l-3 3"/></>,
  Scholar: <><path d="M3 5.5 12 2l9 3.5v11L12 20l-9-3.5z"/><path d="M12 20V8M3 5.5l9 4 9-4"/></>,
  Charisma: <><path d="M3 12c2.4-4.7 6-6.4 9-6.4s6.6 1.7 9 6.4c-2.4 4.7-6 6.4-9 6.4S5.4 16.7 3 12Z"/><path d="M7 12c1.5 1.4 3.2 2.1 5 2.1s3.5-.7 5-2.1"/></>,
  Physical: <><path d="M7 20v-5.2c0-1.3.9-2.3 2.1-2.5l2.4-.4 1.7-4.2c.4-1 1.6-1.4 2.4-.7.6.5.8 1.3.5 2L15 12.2l3.7.7c1.4.3 2.3 1.5 2.3 2.9V20"/><path d="M7 16H4v-3M12 8l-1.4-2.6a1.5 1.5 0 0 1 2.7-1.3L15 6"/></>,
  Artist: <><path d="m14 4 6 6M4 20l1.4-4.6L16.5 4.3a2.1 2.1 0 0 1 3 3L8.4 18.6z"/><path d="m13 7 4 4"/></>,
  Connector: <><path d="m8.5 12.5 2-2a2.1 2.1 0 0 1 3 0l.3.3a2.1 2.1 0 0 1 3 3l-3.2 3.2a3.5 3.5 0 0 1-5 0l-5-5a2.1 2.1 0 0 1 3-3l2 2"/><path d="m12 12 1.2 1.2"/></>,
  Craftsman: <path d="m14.7 6.3 3-3a4.3 4.3 0 0 0-5.5 5.5L4 17a2.1 2.1 0 1 0 3 3l8.2-8.2a4.3 4.3 0 0 0 5.5-5.5l-3 3z"/>,
  Explorer: <><circle cx="12" cy="12" r="8.5"/><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8z"/><path d="M12 3.5v2M20.5 12h-2M12 20.5v-2M3.5 12h2"/></>,
  Merchant: <><path d="M4 9h16l-1 11H5zM6 9a6 6 0 0 1 12 0"/><path d="M9 13a3 3 0 0 0 6 0"/></>,
  Health: <><path d="M20.4 5.8a4.4 4.4 0 0 0-6.2 0L12 8l-2.2-2.2a4.4 4.4 0 0 0-6.2 6.2L12 20.4l8.4-8.4a4.4 4.4 0 0 0 0-6.2Z"/><path d="M7 12h2l1-2 2 4 1-2h4"/></>,
};
function HubIcon({ name, custom }: { name: string; custom?: LucideIcon }) { if (!ICONS[name] && custom) { const C = custom; return <C aria-hidden="true" />; } return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{ICONS[name] || ICONS.Mindset}</svg>; }
function slug(title: string, index: number) { return `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "milestone"}-${index + 1}`; }

export function ConstellationStage({ skills, getMilestones, getCustomIcon, pending, error, onRetry, onToggle, onEditSkill, onDeleteSkill, onAddSkill, onWhySkills, onEditMilestones }: Props) {
  const canonical = useMemo(() => ORDER.map(n => skills.find(s => s.skillName === n)).filter(Boolean) as UserSkill[], [skills]);
  const mapRef = useRef<HTMLElement>(null);
  const [focusId, setFocusId] = useState<number | null>(null); const [nodeId, setNodeId] = useState<string | null>(null);
  const focused = skills.find(s => s.id === focusId); const milestones = focused ? getMilestones(focused) : []; const done = new Set((focused?.completedMilestones as string[] | null) || []); const byId = new Map(milestones.map(m => [m.id, m])); const selected = milestones.find(m => m.id === nodeId);
  const status = (m: ConstellationMilestone) => done.has(m.id) ? "mastered" : m.parents?.length && m.parents.every(p => done.has(p)) ? "available" : m.parents?.length ? "locked" : "progress";
  const cycle = (d: number) => { const i = Math.max(0, canonical.findIndex(s => s.id === focused?.id)); const next = canonical[(i + d + canonical.length) % canonical.length]; if (!next) return; setFocusId(next.id); setNodeId(null); const url = new URL(window.location.href); url.searchParams.set("domain", next.skillName.toLowerCase().replace(/\s+/g, "-")); window.history.pushState({ domain: next.skillName }, "", url); };
  const enter = (skill: UserSkill) => { setFocusId(skill.id); setNodeId(null); const url = new URL(window.location.href); url.searchParams.set("domain", skill.skillName.toLowerCase().replace(/\s+/g, "-")); window.history.pushState({ domain: skill.skillName }, "", url); };
  useEffect(() => { const sync = () => { const q = new URLSearchParams(window.location.search).get("domain"); const s = skills.find(x => x.skillName.toLowerCase().replace(/\s+/g, "-") === q); if (s) setFocusId(s.id); else setFocusId(null); }; sync(); window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, [skills]);
  useEffect(() => { if (mapRef.current) { if (focused) mapRef.current.setAttribute("inert", ""); else mapRef.current.removeAttribute("inert"); } }, [focused]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "Escape" && focused) { setFocusId(null); setNodeId(null); const u = new URL(window.location.href); u.searchParams.delete("domain"); window.history.pushState({}, "", u); } else if (e.key === "ArrowLeft") cycle(-1); else if (e.key === "ArrowRight") cycle(1); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  if (error) return <main className="constellation-stage constellation-error"><h1>Unable to illuminate your skills</h1><p>{error.message || "The constellation could not be loaded."}</p><button onClick={onRetry}>Try again</button></main>;
  return <main className="constellation-stage" aria-label="Life OS skill constellation">
    <section ref={mapRef} className={`constellation-map ${focused ? "is-hidden" : ""}`} aria-label="Ten skill constellation overview" aria-hidden={!!focused}><div className="constellation-nebula"><i /></div><svg className="constellation-lines" viewBox="0 0 100 100" aria-hidden="true">{canonical.map((s, i) => { const a = (-90 + i * 36) * Math.PI / 180; return <path key={s.id} d={`M50 50 L${50 + Math.cos(a) * 24} ${50 + Math.sin(a) * 24}`} />; })}</svg>
      {canonical.map((s, i) => { const a = (-90 + i * 36) * Math.PI / 180; const style = { "--x": `${50 + Math.cos(a) * 24}%`, "--y": `${50 + Math.sin(a) * 24}%`, "--lx": `${50 + Math.cos(a) * 41}%`, "--ly": `${50 + Math.sin(a) * 41}%`, "--tone": COLORS[s.skillName] } as CSSProperties; return <div key={s.id} className="atlas-skill" style={style}><button className="atlas-hub" aria-label={`Open ${s.skillName} skill tree`} onClick={() => enter(s)}><HubIcon name={s.skillName} custom={getCustomIcon(s)} /></button><button className="atlas-label" onClick={() => enter(s)}><b>{s.skillName}</b><small>{DESC[s.skillName] || "personal practice"}</small></button></div>; })}
      <div className="constellation-controls"><button onClick={onWhySkills}>Why skills?</button><button onClick={onAddSkill}>Add skill</button>{skills.filter(s => s.isCustom).map(s => <button key={s.id} onClick={() => enter(s)}>{s.skillName}</button>)}</div><button className="constellation-pager prev" aria-label="Previous skill" onClick={() => enter(canonical.at(-1)!)}>‹</button><button className="constellation-pager next" aria-label="Next skill" onClick={() => enter(canonical[0]!)}>›</button><span className="atlas-caption">Overview · 10 skills</span>
    </section>
    <section className={`constellation-focus ${focused ? "is-active" : ""}`} aria-label={focused ? `${focused.skillName} focused skill tree` : undefined}>{focused && <><svg className="focus-lines" viewBox="0 0 100 100" aria-hidden="true">{milestones.flatMap(m => (m.parents || []).map(p => { const q = byId.get(p); return q ? <line key={`${p}-${m.id}`} x1={q.x} y1={q.y} x2={m.x} y2={m.y} className={status(m) === "locked" ? "faint" : ""} /> : null; }))}</svg>{milestones.map(m => <button key={m.id} className={`focus-node ${status(m)}`} style={{ left: `${m.x}%`, top: `${m.y}%` }} aria-label={`${m.title}, ${status(m)}`} disabled={pending} onClick={() => setNodeId(m.id)} />)}<div className="focus-hub" style={{ "--tone": COLORS[focused.skillName] || "#b596ee" } as CSSProperties}><HubIcon name={focused.skillName} custom={getCustomIcon(focused)} /></div><div className="focus-title"><b>{focused.skillName}</b><small>{DESC[focused.skillName] || "personal practice"} · Level {focused.level} · {focused.xp}/{focused.maxXp} XP</small></div><button className="focus-back" onClick={() => { setFocusId(null); setNodeId(null); const u = new URL(window.location.href); u.searchParams.delete("domain"); window.history.pushState({}, "", u); }}>‹ All skills</button><button className="constellation-pager prev" aria-label="Previous skill" onClick={() => cycle(-1)}>‹</button><button className="constellation-pager next" aria-label="Next skill" onClick={() => cycle(1)}>›</button>
      <aside className={`node-inspector ${selected ? "show" : ""}`} aria-live="polite">{selected && <><span>{status(selected)} · {selected.id}</span><h2>{selected.title}</h2><p>{selected.parents?.length ? `Prerequisites: ${selected.parents.map(p => byId.get(p)?.title).filter(Boolean).join(" · ")}` : "Foundation milestone · no prerequisites"}</p><small>{done.has(selected.id) ? "Path illuminated · complete" : status(selected) === "available" ? "Prerequisite met · ready" : "Prerequisite path still forming"}</small><div className="inspector-actions"><button disabled={pending || status(selected) === "locked"} onClick={() => { onToggle(focused.id, selected.id); setNodeId(null); }}>{pending ? "Saving…" : done.has(selected.id) ? "Dim this node" : "Light this node"}</button><button onClick={() => setNodeId(null)}>Close</button></div></>}</aside><div className="focus-low-controls"><button onClick={() => onEditSkill(focused)}>{focused.isCustom ? "Edit icon / level / XP" : "Edit level / XP"}</button><button onClick={() => onEditMilestones(focused)}>Customize milestones</button>{focused.isCustom && <button onClick={() => onDeleteSkill(focused)}>Delete skill</button>}</div></>}</section>
  </main>;
}